openapi: 3.0.3
info:
  title: My Fruity API
  version: 1.0.0
servers:
  - url: https://localhost:7271
    description: Local server
paths:
  /fruits:
    get:
      summary: Get all fruits
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fruit'
  /fruits/{name}:
    get:
      summary: Get a fruit by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fruit'
  /echofruitAsJson:
    post:
      summary: Echo a fruit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fruit'
  /echofruitAsCbor:
    post:
      summary: Echo a fruit
      requestBody:
        required: true
        content:
          application/cbor:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        '200':
          description: OK
          content:
            application/cbor:
              schema:
                $ref: '#/components/schemas/Fruit'
  /meteoriteLandings:
    get:
      summary: Get all meteorite landings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/meteoriteLanding'
    post:
      summary: Create a meteorite landings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/meteoriteLanding'
      responses:
        '204':
          description: Created

components:
  schemas:
    meteoriteLanding:
      type: object
      properties:
        id:
          type: number
          format: int64
        name:
          type: string
        fall:
          type: string
        geolocation:
          $ref: '#/components/schemas/Geolocation'
        mass:
          type: number
          format: double
        nametype:
          type: string
        recclass:
          type: string
        reclat:
          type: number
          format: double
        reclong:
          type: number
          format: double
        year:
          type: string
          format: date
    Geolocation:
      type: object
      properties:
        type:
          type: string
        coordinates:
          type: array
          items:
            type: number
            format: double
    Fruit:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
        weight:
          type: number
        citrus:
          type: boolean
        description:
          type: string
        createdDateTime:
          type: string
          format: date-time
        lastModifiedDateTime:
          type: string
          format: date-time
