// <auto-generated/>
using KiotaFruit.EchofruitAsCbor;
using KiotaFruit.EchofruitAsJson;
using KiotaFruit.Fruits;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Cbor;
using Microsoft.Kiota.Serialization.Json;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaFruit {
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    public class FruitClient : BaseRequestBuilder {
        /// <summary>The echofruitAsCbor property</summary>
        public EchofruitAsCborRequestBuilder EchofruitAsCbor { get =>
            new EchofruitAsCborRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The echofruitAsJson property</summary>
        public EchofruitAsJsonRequestBuilder EchofruitAsJson { get =>
            new EchofruitAsJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fruits property</summary>
        public FruitsRequestBuilder Fruits { get =>
            new FruitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new FruitClient and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FruitClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>()) {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<CborSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<CborParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl)) {
                RequestAdapter.BaseUrl = "https://localhost:7271";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
